name: Release
on:
  pull_request:
  push:
    branches: [master, main]
  release:
    types: [published]
jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'
      - run: sbt check

  publishLocal:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 8
          cache: 'sbt'
      - run: sbt +publishLocal

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'
      - run: sbt +test

  ci:
    runs-on: ubuntu-22.04
    needs: [lint, publishLocal, test]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"

  publish:
    runs-on: ubuntu-22.04
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 8
          cache: 'sbt'
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
